# Configure the name of this CI unit. This is the name that appears in the GitHub Actions tab
name: CiCd
# Configure what events trigger this action.
on: [push]

# Configure environment variables that are global to the action defined by this file
env:
  #OPENTAP_COLOR: auto # github messes with the "auto" color detection (i.e. it has no effect), and the "always" option breaks a lot of things
  OPENTAP_ANSI_COLORS: true
  OPENTAP_NO_UPDATE_CHECK: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_CONSOLE_ANSI_COLOR: true

jobs:

  ##############
  ### BUILD   ##
  ##############

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup OpenTAP
        uses: opentap/setup-opentap@main
        with:
          version: 9.23.0
          packages: 'DocumentationGeneration:1.0.2'
          additional-repository: 'https://test-automation.pw.keysight.com/api/packages'
          additional-repository-token: '${{ secrets.KS8500_REPO_TOKEN }}'
      - run:
          tap generate-chm "Documents/Readme.md" --out Help/SpreadsheetHelp.chm --title "Keysight TAP Spreadsheet Plugin Help" --startpage "Documents/GettingStarted/GettingStarted.md" --css "Documents/Style.css" --startpage-title "Spreadsheet Plugin Help"
      - name: Fix tags
        shell: bash
        if: github.ref_type == 'tag'
        # Fixes an issue with actions/checkout@{v2,v3,v4} - see https://github.com/actions/checkout/issues/290
        run: git fetch --force --tags origin
      # Build your project
      - name: Build
        run: dotnet build -c Release
      # Upload the package so it can be downloaded from GitHub, 
      # and consumed by other steps in this workflow
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: tap-package
          retention-days: 7
          path: |
            OpenTap.Plugins.Spreadsheet/bin/Release/netstandard2.0/*.TapPackage
  ##############
  ### PUBLISH ##
  ##############

  Publish:
    # Only publish on the main branch or if the commit is tagged.
    if: github.ref == 'refs/heads/main' || contains(github.ref, 'refs/heads/release') || contains(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    # This step depends on the build step
    needs:
      - Build
    steps:
      # Download the tap-package artifact from the Build step
      - name: Download TapPackage Arfifact
        uses: actions/download-artifact@v4
        with:
          name: tap-package
          path: .
      # Setup OpenTAP with the PackagePublish package in order to publish the newly created package
      - name: Setup OpenTAP
        uses: opentap/setup-opentap@v1.0
        with:
          version: 9.20.0
          packages: "Repository Client:beta"
      # Publish the package. This requires the package management key to be configured in the 'PUBLIC_REPO_PASS' environment variable.
      - name: Publish Packages
        working-directory: ./
        run: tap repo upload --repository http://packages.opentap.io --token ${{ secrets.PUBLIC_REPO_PASS }} Spreadsheet*.TapPackage